<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentMigrator" Version="6.2.0" />
    <PackageReference Include="FluentMigrator.Runner" Version="6.2.0" />
    <PackageReference Include="FluentMigrator.Runner.SQLite" Version="6.2.0" />
    <PackageReference Include="linq2db" Version="5.4.1" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.2" />
  </ItemGroup>

</Project>
