// <auto-generated />
using FeintSite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace FeintSite.Migrations
{
    [DbContext(typeof(Db))]
    partial class DbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("FeintSDK.SessionKey", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Key");

                    b.Property<int>("SessionKeyId");

                    b.HasKey("Id");

                    b.ToTable("SessionKey");
                });

            modelBuilder.Entity("FeintSDK.SessionProperty", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int?>("OwnerId");

                    b.Property<int>("SessionPropertyId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("SessionProperty");
                });

            modelBuilder.Entity("FeintSite.ExampleModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ExamplePropertyInteger");

                    b.Property<string>("ExamplePropertyString");

                    b.HasKey("Id");

                    b.ToTable("ExampleModel");
                });

            modelBuilder.Entity("FeintSDK.SessionProperty", b =>
                {
                    b.HasOne("FeintSDK.SessionKey", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");
                });
#pragma warning restore 612, 618
        }
    }
}
