<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
      <ProjectReference Include="..\FeintFramework.Db\FeintFramework.Db.csproj" />
      <ProjectReference Include="..\FeintFramework.Core\FeintFramework.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
      <None Update="**\*.html">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
  </ItemGroup>
  <ItemGroup>
    <Watch Include="**\*.html" />
  </ItemGroup>
</Project>
